#!/usr/bin/env bash
#
# Regenerate db/schema.generated.sql — a human-readable view of the full engine
# schema (structure from db/migrations/ + functions/views/triggers from
# db/engine/), produced deterministically in a throwaway Postgres container.
#
# On-demand only — the output (db/schema.generated.sql) is gitignored, not
# checked in, and there is no CI freshness gate (drift is structurally impossible
# under migrations-only; see docs/adr/0001-schema-migrations.md). Run it whenever
# you want a current human-readable view of the full schema:
#   ./scripts/gen-schema.sh
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT/db/engine/manifest.sh"

PORT="${GEN_SCHEMA_PORT:-55459}"
NAME="pgauthz-genschema-$$"
SQLX="${SQLX_BIN:-sqlx}"
command -v "$SQLX" >/dev/null 2>&1 || SQLX="$HOME/.cargo/bin/sqlx"

cleanup() { docker rm -f "$NAME" >/dev/null 2>&1 || true; }
trap cleanup EXIT

docker run -d --name "$NAME" \
  -e POSTGRES_USER=authz -e POSTGRES_PASSWORD=authz -e POSTGRES_DB=authz \
  -p "$PORT:5432" -v "$ROOT":/repo:ro postgres:18.4 >/dev/null

for _ in $(seq 1 60); do docker exec "$NAME" pg_isready -U authz >/dev/null 2>&1 && break; sleep 1; done

# Structure via migrations, then the idempotent engine code. No
# ensure_audit_partitions() — the runtime monthly partitions would make the
# dump non-deterministic.
DATABASE_URL="postgres://authz:authz@localhost:$PORT/authz" "$SQLX" migrate run --source "$ROOT/db/migrations"
while IFS= read -r f; do
  docker exec "$NAME" psql -U authz -d authz -q -v ON_ERROR_STOP=1 -f "/repo/db/engine/$f" >/dev/null
done < <(engine_files_for substrate read write audit)

{
  echo "-- Generated by ./scripts/gen-schema.sh (pg_dump --schema-only -n authz after a"
  echo "-- clean \`sqlx migrate run\` + engine code load). DO NOT EDIT."
  echo "-- A human-readable view of the full engine schema (structure from db/migrations/ +"
  echo "-- functions/views/triggers from db/engine/). Excludes runtime monthly audit partitions."
  echo "-- On-demand reference, gitignored — regenerate with ./scripts/gen-schema.sh."
  echo
  # Strip pg_dump's \restrict/\unrestrict guard lines — they carry a random
  # nonce that would make the output non-deterministic.
  docker exec "$NAME" pg_dump -U authz -d authz --schema-only --no-owner --no-privileges -n authz \
    | sed '/^\\restrict /d; /^\\unrestrict /d'
} > "$ROOT/db/schema.generated.sql"

echo "==> Wrote db/schema.generated.sql ($(wc -l < "$ROOT/db/schema.generated.sql") lines)"
